default_language_version:
  python: python3.13
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.13.0'
  hooks:
    - id: ruff-check
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
